<?xml version="1.0" ?>
<!DOCTYPE AgeGroup [
  <!ELEMENT AgeGroup (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (age_group_id?,age_name?,age_description?)+>
  <!ELEMENT age_group_id (#PCDATA)>
  <!ELEMENT age_name (#PCDATA)>
  <!ELEMENT age_description (#PCDATA)>
]>
<AgeGroup>
  <DATA_RECORD>
    <age_group_id>1</age_group_id>
    <age_name>Seniors</age_name>
    <age_description>65+</age_description>
  </DATA_RECORD>
  <DATA_RECORD>
    <age_group_id>2</age_group_id>
    <age_name>Veterans</age_name>
    <age_description>55+</age_description>
  </DATA_RECORD>
  <DATA_RECORD>
    <age_group_id>3</age_group_id>
    <age_name>Adults</age_name>
    <age_description>21-54</age_description>
  </DATA_RECORD>
  <DATA_RECORD>
    <age_group_id>4</age_group_id>
    <age_name>Young Adults</age_name>
    <age_description>17-20</age_description>
  </DATA_RECORD>
  <DATA_RECORD>
    <age_group_id>5</age_group_id>
    <age_name>Juniors</age_name>
    <age_description>13-16</age_description>
  </DATA_RECORD>
  <DATA_RECORD>
    <age_group_id>6</age_group_id>
    <age_name>Cubs</age_name>
    <age_description>under 13</age_description>
  </DATA_RECORD>
</AgeGroup>
