<?xml version="1.0" ?>
<!DOCTYPE Competitor [
  <!ELEMENT Competitor (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (player_id?,bow_id?,skill_id?,division_id?,age_group_id?,tournament_id?,payment_id?,fname?,lname?,date_of_birth?,country?,mail?,gender?,accomodation?,comment?)+>
  <!ELEMENT player_id (#PCDATA)>
  <!ELEMENT bow_id (#PCDATA)>
  <!ELEMENT skill_id (#PCDATA)>
  <!ELEMENT division_id (#PCDATA)>
  <!ELEMENT age_group_id (#PCDATA)>
  <!ELEMENT tournament_id (#PCDATA)>
  <!ELEMENT payment_id (#PCDATA)>
  <!ELEMENT fname (#PCDATA)>
  <!ELEMENT lname (#PCDATA)>
  <!ELEMENT date_of_birth (#PCDATA)>
  <!ELEMENT country (#PCDATA)>
  <!ELEMENT mail (#PCDATA)>
  <!ELEMENT gender (#PCDATA)>
  <!ELEMENT accomodation (#PCDATA)>
  <!ELEMENT comment (#PCDATA)>
]>
<Competitor>
  <DATA_RECORD>
    <player_id>1</player_id>
    <bow_id>10</bow_id>
    <skill_id>1</skill_id>
    <division_id>109</division_id>
    <age_group_id>1</age_group_id>
    <tournament_id>1</tournament_id>
    <payment_id>1</payment_id>
    <fname>Karin</fname>
    <lname>Sch√∂neich</lname>
    <date_of_birth>1953-02-12</date_of_birth>
    <country>Germany</country>
    <mail>karin.schoneich@example.com</mail>
    <gender>F</gender>
    <accomodation></accomodation>
    <comment></comment>
  </DATA_RECORD>
  <DATA_RECORD>
    <player_id>2</player_id>
    <bow_id>10</bow_id>
    <skill_id>1</skill_id>
    <division_id>109</division_id>
    <age_group_id>1</age_group_id>
    <tournament_id>1</tournament_id>
    <payment_id>2</payment_id>
    <fname>Magdalena</fname>
    <lname>Dzielska</lname>
    <date_of_birth>1950-08-12</date_of_birth>
    <country>Poland</country>
    <mail>magdalena.zie@example.com</mail>
    <gender>F</gender>
    <accomodation></accomodation>
    <comment></comment>
  </DATA_RECORD>
  <DATA_RECORD>
    <player_id>3</player_id>
    <bow_id>10</bow_id>
    <skill_id>1</skill_id>
    <division_id>109</division_id>
    <age_group_id>1</age_group_id>
    <tournament_id>1</tournament_id>
    <payment_id>3</payment_id>
    <fname>Hildegard</fname>
    <lname>Schneider</lname>
    <date_of_birth>1931-02-12</date_of_birth>
    <country>Austria</country>
    <mail>hildi@example.com</mail>
    <gender>F</gender>
    <accomodation></accomodation>
    <comment></comment>
  </DATA_RECORD>
  <DATA_RECORD>
    <player_id>4</player_id>
    <bow_id>10</bow_id>
    <skill_id>1</skill_id>
    <division_id>109</division_id>
    <age_group_id>1</age_group_id>
    <tournament_id>1</tournament_id>
    <payment_id>4</payment_id>
    <fname>Daniela</fname>
    <lname>Schneider</lname>
    <date_of_birth>1941-06-12</date_of_birth>
    <country>Austria</country>
    <mail>dani@example.com</mail>
    <gender>F</gender>
    <accomodation></accomodation>
    <comment></comment>
  </DATA_RECORD>
  <DATA_RECORD>
    <player_id>5</player_id>
    <bow_id>10</bow_id>
    <skill_id>1</skill_id>
    <division_id>109</division_id>
    <age_group_id>1</age_group_id>
    <tournament_id>1</tournament_id>
    <payment_id>5</payment_id>
    <fname>Michaela</fname>
    <lname>Denier</lname>
    <date_of_birth>1945-09-02</date_of_birth>
    <country>Switzerland</country>
    <mail>michieale@example.com</mail>
    <gender>F</gender>
    <accomodation></accomodation>
    <comment></comment>
  </DATA_RECORD>
  <DATA_RECORD>
    <player_id>6</player_id>
    <bow_id>5</bow_id>
    <skill_id>1</skill_id>
    <division_id>50</division_id>
    <age_group_id>1</age_group_id>
    <tournament_id>1</tournament_id>
    <payment_id>6</payment_id>
    <fname>Franco</fname>
    <lname>Zuur</lname>
    <date_of_birth>1953-02-12</date_of_birth>
    <country>Germany</country>
    <mail>franco.zuur@example.com</mail>
    <gender>M</gender>
    <accomodation></accomodation>
    <comment></comment>
  </DATA_RECORD>
  <DATA_RECORD>
    <player_id>7</player_id>
    <bow_id>5</bow_id>
    <skill_id>1</skill_id>
    <division_id>50</division_id>
    <age_group_id>1</age_group_id>
    <tournament_id>1</tournament_id>
    <payment_id>7</payment_id>
    <fname>Axel</fname>
    <lname>Bothma</lname>
    <date_of_birth>1950-08-12</date_of_birth>
    <country>Poland</country>
    <mail>axel.bothma@example.com</mail>
    <gender>M</gender>
    <accomodation></accomodation>
    <comment></comment>
  </DATA_RECORD>
  <DATA_RECORD>
    <player_id>8</player_id>
    <bow_id>5</bow_id>
    <skill_id>1</skill_id>
    <division_id>50</division_id>
    <age_group_id>1</age_group_id>
    <tournament_id>1</tournament_id>
    <payment_id>8</payment_id>
    <fname>James</fname>
    <lname>Kruger</lname>
    <date_of_birth>1931-02-12</date_of_birth>
    <country>Austria</country>
    <mail>james@example.com</mail>
    <gender>M</gender>
    <accomodation></accomodation>
    <comment></comment>
  </DATA_RECORD>
  <DATA_RECORD>
    <player_id>9</player_id>
    <bow_id>5</bow_id>
    <skill_id>1</skill_id>
    <division_id>50</division_id>
    <age_group_id>1</age_group_id>
    <tournament_id>1</tournament_id>
    <payment_id>9</payment_id>
    <fname>Johann</fname>
    <lname>Bronkhorst</lname>
    <date_of_birth>1941-06-12</date_of_birth>
    <country>Austria</country>
    <mail>johann@example.com</mail>
    <gender>M</gender>
    <accomodation></accomodation>
    <comment></comment>
  </DATA_RECORD>
  <DATA_RECORD>
    <player_id>10</player_id>
    <bow_id>5</bow_id>
    <skill_id>1</skill_id>
    <division_id>50</division_id>
    <age_group_id>1</age_group_id>
    <tournament_id>1</tournament_id>
    <payment_id>10</payment_id>
    <fname>Canell</fname>
    <lname>Jackson</lname>
    <date_of_birth>1945-09-02</date_of_birth>
    <country>Switzerland</country>
    <mail>canell@example.com</mail>
    <gender>M</gender>
    <accomodation></accomodation>
    <comment></comment>
  </DATA_RECORD>
</Competitor>
