<?xml version="1.0" ?>
<!DOCTYPE Scorecard [
  <!ELEMENT Scorecard (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (scorecard_id?,date?,player_id?,writer_id?,tournament_id?,round_id?)+>
  <!ELEMENT scorecard_id (#PCDATA)>
  <!ELEMENT date (#PCDATA)>
  <!ELEMENT player_id (#PCDATA)>
  <!ELEMENT writer_id (#PCDATA)>
  <!ELEMENT tournament_id (#PCDATA)>
  <!ELEMENT round_id (#PCDATA)>
]>
<Scorecard>
  <DATA_RECORD>
    <scorecard_id>1</scorecard_id>
    <date>2020-08-03</date>
    <player_id>1</player_id>
    <writer_id>1</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>2</scorecard_id>
    <date>2020-08-03</date>
    <player_id>2</player_id>
    <writer_id>1</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>3</scorecard_id>
    <date>2020-08-03</date>
    <player_id>3</player_id>
    <writer_id>1</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>4</scorecard_id>
    <date>2020-08-03</date>
    <player_id>4</player_id>
    <writer_id>1</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>5</scorecard_id>
    <date>2020-08-03</date>
    <player_id>5</player_id>
    <writer_id>1</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>6</scorecard_id>
    <date>2020-08-03</date>
    <player_id>1</player_id>
    <writer_id>2</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>7</scorecard_id>
    <date>2020-08-03</date>
    <player_id>2</player_id>
    <writer_id>2</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>8</scorecard_id>
    <date>2020-08-03</date>
    <player_id>3</player_id>
    <writer_id>2</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>9</scorecard_id>
    <date>2020-08-03</date>
    <player_id>4</player_id>
    <writer_id>2</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>10</scorecard_id>
    <date>2020-08-03</date>
    <player_id>5</player_id>
    <writer_id>2</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>11</scorecard_id>
    <date>2020-08-04</date>
    <player_id>1</player_id>
    <writer_id>3</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>12</scorecard_id>
    <date>2020-08-04</date>
    <player_id>2</player_id>
    <writer_id>3</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>13</scorecard_id>
    <date>2020-08-04</date>
    <player_id>3</player_id>
    <writer_id>3</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>14</scorecard_id>
    <date>2020-08-04</date>
    <player_id>4</player_id>
    <writer_id>3</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>15</scorecard_id>
    <date>2020-08-04</date>
    <player_id>5</player_id>
    <writer_id>3</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>16</scorecard_id>
    <date>2020-08-04</date>
    <player_id>1</player_id>
    <writer_id>4</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>17</scorecard_id>
    <date>2020-08-04</date>
    <player_id>2</player_id>
    <writer_id>4</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>18</scorecard_id>
    <date>2020-08-04</date>
    <player_id>3</player_id>
    <writer_id>4</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>19</scorecard_id>
    <date>2020-08-04</date>
    <player_id>4</player_id>
    <writer_id>4</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>20</scorecard_id>
    <date>2020-08-04</date>
    <player_id>5</player_id>
    <writer_id>4</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>21</scorecard_id>
    <date>2020-08-05</date>
    <player_id>1</player_id>
    <writer_id>5</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>22</scorecard_id>
    <date>2020-08-05</date>
    <player_id>2</player_id>
    <writer_id>5</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>23</scorecard_id>
    <date>2020-08-05</date>
    <player_id>3</player_id>
    <writer_id>5</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>24</scorecard_id>
    <date>2020-08-05</date>
    <player_id>4</player_id>
    <writer_id>5</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>25</scorecard_id>
    <date>2020-08-05</date>
    <player_id>5</player_id>
    <writer_id>5</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>26</scorecard_id>
    <date>2020-08-05</date>
    <player_id>1</player_id>
    <writer_id>3</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>27</scorecard_id>
    <date>2020-08-05</date>
    <player_id>2</player_id>
    <writer_id>3</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>28</scorecard_id>
    <date>2020-08-05</date>
    <player_id>3</player_id>
    <writer_id>3</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>29</scorecard_id>
    <date>2020-08-05</date>
    <player_id>4</player_id>
    <writer_id>3</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>30</scorecard_id>
    <date>2020-08-05</date>
    <player_id>5</player_id>
    <writer_id>3</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>31</scorecard_id>
    <date>2020-08-06</date>
    <player_id>1</player_id>
    <writer_id>2</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>32</scorecard_id>
    <date>2020-08-06</date>
    <player_id>2</player_id>
    <writer_id>2</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>33</scorecard_id>
    <date>2020-08-06</date>
    <player_id>3</player_id>
    <writer_id>2</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>34</scorecard_id>
    <date>2020-08-06</date>
    <player_id>4</player_id>
    <writer_id>2</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>35</scorecard_id>
    <date>2020-08-06</date>
    <player_id>5</player_id>
    <writer_id>2</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>36</scorecard_id>
    <date>2020-08-06</date>
    <player_id>1</player_id>
    <writer_id>5</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>37</scorecard_id>
    <date>2020-08-06</date>
    <player_id>2</player_id>
    <writer_id>5</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>38</scorecard_id>
    <date>2020-08-06</date>
    <player_id>3</player_id>
    <writer_id>5</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>39</scorecard_id>
    <date>2020-08-06</date>
    <player_id>4</player_id>
    <writer_id>5</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>40</scorecard_id>
    <date>2020-08-06</date>
    <player_id>5</player_id>
    <writer_id>5</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>41</scorecard_id>
    <date>2020-08-07</date>
    <player_id>1</player_id>
    <writer_id>1</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>42</scorecard_id>
    <date>2020-08-07</date>
    <player_id>2</player_id>
    <writer_id>1</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>43</scorecard_id>
    <date>2020-08-07</date>
    <player_id>3</player_id>
    <writer_id>1</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>44</scorecard_id>
    <date>2020-08-07</date>
    <player_id>4</player_id>
    <writer_id>1</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>45</scorecard_id>
    <date>2020-08-07</date>
    <player_id>5</player_id>
    <writer_id>1</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>46</scorecard_id>
    <date>2020-08-07</date>
    <player_id>1</player_id>
    <writer_id>4</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>47</scorecard_id>
    <date>2020-08-07</date>
    <player_id>2</player_id>
    <writer_id>4</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>48</scorecard_id>
    <date>2020-08-07</date>
    <player_id>3</player_id>
    <writer_id>4</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>49</scorecard_id>
    <date>2020-08-07</date>
    <player_id>4</player_id>
    <writer_id>4</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>50</scorecard_id>
    <date>2020-08-07</date>
    <player_id>5</player_id>
    <writer_id>4</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>51</scorecard_id>
    <date>2020-08-03</date>
    <player_id>6</player_id>
    <writer_id>6</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>52</scorecard_id>
    <date>2020-08-03</date>
    <player_id>7</player_id>
    <writer_id>6</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>53</scorecard_id>
    <date>2020-08-03</date>
    <player_id>8</player_id>
    <writer_id>6</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>54</scorecard_id>
    <date>2020-08-03</date>
    <player_id>9</player_id>
    <writer_id>6</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>55</scorecard_id>
    <date>2020-08-03</date>
    <player_id>10</player_id>
    <writer_id>6</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>56</scorecard_id>
    <date>2020-08-03</date>
    <player_id>6</player_id>
    <writer_id>7</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>57</scorecard_id>
    <date>2020-08-03</date>
    <player_id>7</player_id>
    <writer_id>7</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>58</scorecard_id>
    <date>2020-08-03</date>
    <player_id>8</player_id>
    <writer_id>7</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>59</scorecard_id>
    <date>2020-08-03</date>
    <player_id>9</player_id>
    <writer_id>7</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>60</scorecard_id>
    <date>2020-08-03</date>
    <player_id>10</player_id>
    <writer_id>7</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>1</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>61</scorecard_id>
    <date>2020-08-04</date>
    <player_id>6</player_id>
    <writer_id>8</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>62</scorecard_id>
    <date>2020-08-04</date>
    <player_id>7</player_id>
    <writer_id>8</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>63</scorecard_id>
    <date>2020-08-04</date>
    <player_id>8</player_id>
    <writer_id>8</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>64</scorecard_id>
    <date>2020-08-04</date>
    <player_id>9</player_id>
    <writer_id>8</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>65</scorecard_id>
    <date>2020-08-04</date>
    <player_id>10</player_id>
    <writer_id>8</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>66</scorecard_id>
    <date>2020-08-04</date>
    <player_id>6</player_id>
    <writer_id>9</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>67</scorecard_id>
    <date>2020-08-04</date>
    <player_id>7</player_id>
    <writer_id>9</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>68</scorecard_id>
    <date>2020-08-04</date>
    <player_id>8</player_id>
    <writer_id>9</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>69</scorecard_id>
    <date>2020-08-04</date>
    <player_id>9</player_id>
    <writer_id>9</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>70</scorecard_id>
    <date>2020-08-04</date>
    <player_id>10</player_id>
    <writer_id>9</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>2</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>71</scorecard_id>
    <date>2020-08-05</date>
    <player_id>6</player_id>
    <writer_id>10</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>72</scorecard_id>
    <date>2020-08-05</date>
    <player_id>7</player_id>
    <writer_id>10</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>73</scorecard_id>
    <date>2020-08-05</date>
    <player_id>8</player_id>
    <writer_id>10</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>74</scorecard_id>
    <date>2020-08-05</date>
    <player_id>9</player_id>
    <writer_id>10</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>75</scorecard_id>
    <date>2020-08-05</date>
    <player_id>10</player_id>
    <writer_id>10</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>76</scorecard_id>
    <date>2020-08-05</date>
    <player_id>6</player_id>
    <writer_id>8</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>77</scorecard_id>
    <date>2020-08-05</date>
    <player_id>7</player_id>
    <writer_id>8</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>78</scorecard_id>
    <date>2020-08-05</date>
    <player_id>8</player_id>
    <writer_id>8</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>79</scorecard_id>
    <date>2020-08-05</date>
    <player_id>9</player_id>
    <writer_id>8</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>80</scorecard_id>
    <date>2020-08-05</date>
    <player_id>10</player_id>
    <writer_id>8</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>3</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>81</scorecard_id>
    <date>2020-08-06</date>
    <player_id>6</player_id>
    <writer_id>7</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>82</scorecard_id>
    <date>2020-08-06</date>
    <player_id>7</player_id>
    <writer_id>7</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>83</scorecard_id>
    <date>2020-08-06</date>
    <player_id>8</player_id>
    <writer_id>7</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>84</scorecard_id>
    <date>2020-08-06</date>
    <player_id>9</player_id>
    <writer_id>7</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>85</scorecard_id>
    <date>2020-08-06</date>
    <player_id>10</player_id>
    <writer_id>7</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>86</scorecard_id>
    <date>2020-08-06</date>
    <player_id>6</player_id>
    <writer_id>10</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>87</scorecard_id>
    <date>2020-08-06</date>
    <player_id>7</player_id>
    <writer_id>10</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>88</scorecard_id>
    <date>2020-08-06</date>
    <player_id>8</player_id>
    <writer_id>10</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>89</scorecard_id>
    <date>2020-08-06</date>
    <player_id>9</player_id>
    <writer_id>10</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>90</scorecard_id>
    <date>2020-08-06</date>
    <player_id>10</player_id>
    <writer_id>10</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>4</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>91</scorecard_id>
    <date>2020-08-07</date>
    <player_id>6</player_id>
    <writer_id>6</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>92</scorecard_id>
    <date>2020-08-07</date>
    <player_id>7</player_id>
    <writer_id>6</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>93</scorecard_id>
    <date>2020-08-07</date>
    <player_id>8</player_id>
    <writer_id>6</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>94</scorecard_id>
    <date>2020-08-07</date>
    <player_id>9</player_id>
    <writer_id>6</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>95</scorecard_id>
    <date>2020-08-07</date>
    <player_id>10</player_id>
    <writer_id>6</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>96</scorecard_id>
    <date>2020-08-07</date>
    <player_id>6</player_id>
    <writer_id>8</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>97</scorecard_id>
    <date>2020-08-07</date>
    <player_id>7</player_id>
    <writer_id>8</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>98</scorecard_id>
    <date>2020-08-07</date>
    <player_id>8</player_id>
    <writer_id>8</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>99</scorecard_id>
    <date>2020-08-07</date>
    <player_id>9</player_id>
    <writer_id>8</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <scorecard_id>100</scorecard_id>
    <date>2020-08-07</date>
    <player_id>10</player_id>
    <writer_id>8</writer_id>
    <tournament_id>1</tournament_id>
    <round_id>5</round_id>
  </DATA_RECORD>
</Scorecard>
