<?xml version="1.0" ?>
<!DOCTYPE ScoreLine [
  <!ELEMENT ScoreLine (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (station_id?,scorecard_id?)+>
  <!ELEMENT station_id (#PCDATA)>
  <!ELEMENT scorecard_id (#PCDATA)>
]>
<ScoreLine>
  <DATA_RECORD>
    <station_id>1</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>1</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>2</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>2</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>3</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>3</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>4</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>4</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>5</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>5</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>6</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>6</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>7</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>7</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>8</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>8</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>9</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>9</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>10</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>10</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>11</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>11</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>12</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>12</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>13</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>13</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>14</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>14</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>15</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>15</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>16</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>16</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>17</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>17</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>18</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>18</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>19</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>19</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>20</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>20</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>21</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>21</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>22</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>22</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>23</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>23</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>24</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>24</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>25</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>25</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>26</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>26</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>27</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>27</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>28</station_id>
    <scorecard_id>1</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>28</station_id>
    <scorecard_id>6</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>1</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>1</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>2</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>2</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>3</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>3</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>4</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>4</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>5</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>5</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>6</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>6</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>7</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>7</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>8</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>8</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>9</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>9</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>10</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>10</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>11</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>11</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>12</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>12</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>13</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>13</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>14</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>14</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>15</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>15</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>16</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>16</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>17</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>17</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>18</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>18</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>19</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>19</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>20</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>20</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>21</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>21</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>22</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>22</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>23</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>23</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>24</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>24</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>25</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>25</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>26</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>26</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>27</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>27</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>28</station_id>
    <scorecard_id>2</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>28</station_id>
    <scorecard_id>7</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>1</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>1</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>2</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>2</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>3</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>3</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>4</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>4</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>5</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>5</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>6</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>6</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>7</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>7</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>8</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>8</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>9</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>9</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>10</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>10</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>11</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>11</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>12</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>12</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>13</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>13</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>14</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>14</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>15</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>15</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>16</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>16</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>17</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>17</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>18</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>18</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>19</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>19</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>20</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>20</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>21</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>21</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>22</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>22</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>23</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>23</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>24</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>24</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>25</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>25</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>26</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>26</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>27</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>27</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>28</station_id>
    <scorecard_id>3</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>28</station_id>
    <scorecard_id>8</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>1</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>1</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>2</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>2</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>3</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>3</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>4</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>4</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>5</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>5</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>6</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>6</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>7</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>7</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>8</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>8</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>9</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>9</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>10</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>10</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>11</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>11</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>12</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>12</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>13</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>13</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>14</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>14</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>15</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>15</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>16</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>16</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>17</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>17</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>18</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>18</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>19</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>19</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>20</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>20</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>21</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>21</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>22</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>22</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>23</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>23</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>24</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>24</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>25</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>25</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>26</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>26</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>27</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>27</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>28</station_id>
    <scorecard_id>4</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>28</station_id>
    <scorecard_id>9</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>1</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>1</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>2</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>2</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>3</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>3</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>4</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>4</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>5</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>5</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>6</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>6</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>7</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>7</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>8</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>8</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>9</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>9</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>10</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>10</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>11</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>11</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>12</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>12</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>13</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>13</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>14</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>14</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>15</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>15</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>16</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>16</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>17</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>17</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>18</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>18</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>19</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>19</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>20</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>20</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>21</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>21</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>22</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>22</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>23</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>23</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>24</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>24</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>25</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>25</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>26</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>26</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>27</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>27</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>28</station_id>
    <scorecard_id>5</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>28</station_id>
    <scorecard_id>10</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>1</station_id>
    <scorecard_id>11</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>1</station_id>
    <scorecard_id>16</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>2</station_id>
    <scorecard_id>11</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>2</station_id>
    <scorecard_id>16</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>3</station_id>
    <scorecard_id>11</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>3</station_id>
    <scorecard_id>16</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>4</station_id>
    <scorecard_id>11</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>4</station_id>
    <scorecard_id>16</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>5</station_id>
    <scorecard_id>11</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>5</station_id>
    <scorecard_id>16</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>6</station_id>
    <scorecard_id>11</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>6</station_id>
    <scorecard_id>16</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>7</station_id>
    <scorecard_id>11</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>7</station_id>
    <scorecard_id>16</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>8</station_id>
    <scorecard_id>11</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>8</station_id>
    <scorecard_id>16</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>9</station_id>
    <scorecard_id>11</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>
    <station_id>9</station_id>
    <scorecard_id>16</scorecard_id>
  </DATA_RECORD>
  <DATA_RECORD>