<?xml version="1.0" ?>
<!DOCTYPE Tournament [
  <!ELEMENT Tournament (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (tournament_id?,location?,start_date?,end_date?)+>
  <!ELEMENT tournament_id (#PCDATA)>
  <!ELEMENT location (#PCDATA)>
  <!ELEMENT start_date (#PCDATA)>
  <!ELEMENT end_date (#PCDATA)>
]>
<Tournament>
  <DATA_RECORD>
    <tournament_id>1</tournament_id>
    <location>Estonia</location>
    <start_date>2020-07-31</start_date>
    <end_date>2020-08-08</end_date>
  </DATA_RECORD>
</Tournament>
